---
- name: Base post-logs
  hosts: localhost
  gather_facts: false
  roles:
    - generate-zuul-manifest
  tasks:

    - name: Get cloud config from vault
      no_log: true
      vault_cloud_config:
        vault_addr: "{{ zuul_vault_addr }}"
        vault_token: "{{ lookup('file', zuul_base_vault_token_path) }}"
        cloud_secret_path: "{{ vault_cloud_secret_path }}"
        mode: "config"
      register: cloud_config

    - name: Include upload logs role
      no_log: true
      ansible.builtin.include_role:
        name: upload-logs-swift
      vars:
        zuul_log_path_shard_build: true
        zuul_log_cloud_config: '{{ cloud_config.config }}'
        zuul_log_partition: false
        zuul_log_delete_after: 648000
        # Unique log prefix to avoid container name collisions when ceph is
        # used.
        zuul_log_container: zuul-logs
