---
- hosts: all
  tasks:
    - block:
        - ansible.builtin.include_role:
            name: fetch-output
      when:
        - "ansible_connection != 'kubectl'"
        - ansible_user_dir is defined

    - block:
        - ansible.builtin.include_role:
            name: fetch-output-openshift
          vars:
            zuul_log_verbose: true
      when:
        - "ansible_connection == 'kubectl'"
        - ansible_user_dir is defined

    - ansible.builtin.import_role:
        name: merge-output-to-logs
      when: ansible_user_dir is defined

- hosts: all
  ignore_errors: yes
  tasks:
    - block:
        - ansible.builtin.include_role:
            name: remove-build-sshkey
      when:
        - "ansible_connection != 'kubectl'"
        - ansible_user_dir is defined
