---
- name: OpenStack access configuration file
  hosts: all
  become: true
  tasks:
    - name: Ensure openstack directory exists
      ansible.builtin.file:
        path: "/etc/openstack"
        state: "directory"
        mode: "0755"

    - name: Create clouds.yaml
      ansible.builtin.template:
        src: "templates/clouds.yaml.j2"
        dest: "/etc/openstack/clouds.yaml"
        mode: "0400"

    - name: Create secure.yaml
      ansible.builtin.template:
        src: "templates/secure.yaml.j2"
        dest: "/etc/openstack/secure.yaml"
        mode: "0400"
