---
- name: "Request Vault access"
  hosts: localhost
  vars:
    vault_addr: "{{ zuul_vault_addr }}"
    vault_secret_dest: "{{ zuul.executor.work_root }}/.approle-secret"
    vault_token_dest: "{{ zuul.executor.work_root }}/.approle-token"
    vault_role_name: "{{ zuul_vault.vault_role_name }}"

  roles:
    - role: create-vault-approle-token
      vault_role_id: "{{ zuul_vault.vault_role_id }}"
      vault_wrapping_token_id: "{{ lookup('file', vault_secret_dest) }}"

- name: OpenStack access configuration file
  hosts: all
  vars:
    vault_addr: "{{ zuul_vault_addr }}"
    vault_token_dest: "{{ zuul.executor.work_root }}/.approle-token"

  tasks:
    - name: Get cloud config from vault
      no_log: true
      vault_cloud_config:
        vault_addr: "{{ zuul_vault_addr }}"
        vault_token: "{{ lookup('file', zuul_base_vault_token_path) }}"
        cloud_secret_path: "{{ vault_cloud_secret_path }}"
        mode: "config"
      register: cloud_config

    - name: Get temporary application credentials
      openstack_application_credentials:
        cloud: "{{ cloud_config }}"
        name: "functest_{{ zuul.change }}"
      register: app_cred

    - name: Ensure openstack directory exists
      become: true
      ansible.builtin.file:
        path: "/etc/openstack"
        state: "directory"
        mode: "0755"

    - name: Create clouds.yaml
      become: true
      ansible.builtin.template:
        src: "templates/clouds.yaml.j2"
        dest: "/etc/openstack/clouds.yaml"
        mode: "0400"

    - name: Create secure.yaml
      become: true
      ansible.builtin.template:
        src: "templates/secure.yaml.j2"
        dest: "/etc/openstack/secure.yaml"
        mode: "0400"
