---
- name: "Prepare container build environment"
  hosts: all
  tasks:
    - name: Update APT cache  # noqa no-handler
      become: true
      ansible.builtin.apt:
        update_cache: yes
      when:
        - "ansible_os_family == 'Debian'"
