---
- hosts: all
  tasks:
    - name: Update APT cache  # noqa no-handler
      become: true
      ansible.builtin.apt:
        update_cache: yes
      when:
        - "ansible_os_family == 'Debian'"

    - name: Ensure docker is installed
      when: "container_command | default('podman') == 'docker'"
      include_role:
        name: ensure-docker
    - name: Ensure podman is installed
      when: "container_command | default('podman') != 'docker'"
      include_role:
        name: ensure-podman
